---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goz-node
  name: goz-node
spec:
  clusterIP: None
  ports:
  - name: p2p-net-port
    port: 26656
  - name: tendermint-rpc
    port: 26657
  - name: prometheus
    port: 26660
  selector:
    app: goz-node